INSERT INTO Airport (AirportCode, City, State, Country, MaxPlanes) VALUES
('TDL', 'New York City', 'AL', 'Afghanistan', 9),
('PEK', 'Los Angeles', 'AK', 'Albania', 4),
('LHR', 'Chicago', 'AZ', 'Algeria', 11),
('DXB', 'Houston', 'AR', 'Andorra', 2),
('FRA', 'Phoenix', 'CA', 'Angola', 5),
('ICN', 'Philadelphia', 'CO', 'Antigua and Barbuda', 9),
('AMS', 'San Antonio', 'CT', 'Argentina', 1),
('SIN', 'San Diego', 'DE', 'Armenia', 5),
('HKG', 'Dallas', 'FL', 'Australia', 5),
('LAX', 'San Jose', 'GA', 'Austria', 7),
('ORD', 'Austin', 'HI', 'Azerbaijan', 1),
('DEN', 'Jacksonville', 'ID', 'Bahamas', 4),
('YYZ', 'San Francisco', 'IL', 'Bahrain', 1),
('MEX', 'Columbus', 'IN', 'Bangladesh', 6),
('SFO', 'Indianapolis', 'IA', 'Barbados', 5),
('MAD', 'Fort Worth', 'KS', 'Belarus', 7),
('BOM', 'Charlotte', 'KY', 'Belgium', 8),
('CGK', 'Seattle', 'LA', 'Belize', 9),
('MNL', 'Denver', 'ME', 'Benin', 1),
('CAN', 'El Paso', 'MD', 'Bhutan', 1),
('DXG', 'Detroit', 'MA', 'Bolivia', 8),
('ATH', 'Washington, D.C.', 'MI', 'Bosnia and Herzegovina', 3),
('MCO', 'Boston', 'MN', 'Botswana', 7),
('SVO', 'Memphis', 'MS', 'Brazil', 11),
('MSP', 'Nashville', 'MO', 'Brunei', 4),
('YVR', 'Portland', 'MT', 'Bulgaria', 3),
('ZRH', 'Oklahoma City', 'NE', 'Burkina Faso', 1),
('JNB', 'Las Vegas', 'NV', 'Burundi', 7),
('BOG', 'Louisville', 'NH', 'Cabo Verde', 6),
('HNL', 'Baltimore', 'NJ', 'Cambodia', 9),
('MUC', 'Milwaukee', 'NM', 'Cameroon', 1),
('GIG', 'Albuquerque', 'NY', 'Canada', 6),
('TLV', 'Tucson', 'NC', 'Central African Republic', 3),
('MAN', 'Fresno', 'ND', 'Chad', 7),
('KMG', 'Sacramento', 'OH', 'Chile', 2),
('KIX', 'Mesa', 'OK', 'China', 5),
('MSY', 'Kansas City', 'OR', 'Colombia', 7),
('BOS', 'Atlanta', 'PA', 'Comoros', 5),
('TIA', 'Long Beach', 'RI', 'Congo (Congo-Brazzaville)', 11),
('BHX', 'Omaha', 'SC', 'Costa Rica', 1),
('BKK', 'Raleigh', 'SD', 'Croatia', 3),
('LYS', 'Miami', 'TN', 'Cuba', 1),
('BLR', 'Virginia Beach', 'TX', 'Cyprus', 2),
('BUD', 'Oakland', 'UT', 'Czechia (Czech Republic)', 2),
('PTY', 'Minneapolis', 'VT', 'Democratic Republic of the Congo', 6),
('DPS', 'Tulsa', 'VA', 'Denmark', 5),
('NCE', 'Arlington', 'WA', 'Djibouti', 11),
('RDU', 'New Orleans', 'WV', 'Dominica', 1),
('SJC', 'Wichita', 'WI', 'Dominican Republic', 11),
('HAM', 'Cleveland', 'WY', 'East Timor (Timor-Leste)', 7),
('OGG', 'Tampa', 'AL', 'Ecuador', 8),
('DUS', 'Bakersfield', 'AK', 'Egypt', 5),
('STR', 'Aurora', 'AZ', 'El Salvador', 7),
('SDF', 'Anaheim', 'AR', 'Equatorial Guinea', 6),
('CGN', 'Honolulu', 'CA', 'Eritrea', 5),
('ORY', 'Santa Ana', 'CO', 'Estonia', 6),
('MEL', 'Riverside', 'CT', 'Eswatini (fmr. "Swaziland")', 1),
('CTU', 'Corpus Christi', 'DE', 'Ethiopia', 3),
('TLS', 'Lexington', 'FL', 'Fiji', 4),
('TUN', 'Stockton', 'GA', 'Finland', 6),
('HND', 'St. Louis', 'HI', 'France', 1),
('YUL', 'St. Paul', 'ID', 'Gabon', 1),
('NRT', 'Henderson', 'IL', 'Gambia', 5),
('GDL', 'Pittsburgh', 'IN', 'Georgia', 1),
('ZNZ', 'Cincinnati', 'IA', 'Germany', 7),
('MXP', 'Anchorage', 'KS', 'Ghana', 1),
('ATL', 'Greensboro', 'KY', 'Greece', 1),
('KUL', 'Plano', 'LA', 'Grenada', 5),
('LED', 'Newark', 'ME', 'Guatemala', 7),
('TYS', 'Lincoln', 'MD', 'Guinea', 4),
('CMB', 'Orlando', 'MA', 'Guinea-Bissau', 1),
('VIE', 'Irvine', 'MI', 'Guyana', 1),
('FLL', 'Toledo', 'MN', 'Haiti', 4),
('RSW', 'Durham', 'MS', 'Holy See', 8),
('JED', 'Chula Vista', 'MO', 'Honduras', 1),
('AUH', 'Fort Wayne', 'MT', 'Hungary', 1),
('KHH', 'Jersey City', 'NE', 'Iceland', 4),
('NKG', 'St. Petersburg', 'NV', 'India', 2),
('BNE', 'Laredo', 'NH', 'Indonesia', 1),
('KWI', 'Madison', 'NJ', 'Iran', 8),
('DUB', 'Chandler', 'NM', 'Iraq', 2),
('BLQ', 'Buffalo', 'NY', 'Ireland', 1),
('SJU', 'Lubbock', 'NC', 'Israel', 5),
('BSL', 'Scottsdale', 'ND', 'Italy', 9),
('RUH', 'Reno', 'OH', 'Ivory Coast', 4),
('DME', 'Glendale', 'OK', 'Jamaica', 11),
('YOW', 'Gilbert', 'OR', 'Japan', 8),
('NBO', 'Winston-Salem', 'PA', 'Jordan', 5),
('YXE', 'North Las Vegas', 'RI', 'Kazakhstan', 7),
('BOI', 'Norfolk', 'SC', 'Kenya', 7),
('TUS', 'Chesapeake', 'SD', 'Kiribati', 6),
('GVA', 'Garland', 'TN', 'Kuwait', 8),
('PVG', 'Irving', 'TX', 'Kyrgyzstan', 1),
('PLI', 'Hialeah', 'UT', 'Laos', 11),
('LIS', 'Fremont', 'VT', 'Latvia', 1),
('OSL', 'Boise', 'VA', 'Lebanon', 8),
('KEF', 'Richmond', 'WA', 'Lesotho', 4),
('VLC', 'Baton Rouge', 'WV', 'Liberia', 8),
('SEA', 'Spokane', 'WI', 'Libya', 1),
('BRU', 'Des Moines', 'WY', 'Liechtenstein', 2),
('BHM', 'Tacoma', 'AL', 'Lithuania', 1),
('YYC', 'San Bernardino', 'AK', 'Luxembourg', 9),
('AUS', 'Modesto', 'AZ', 'Madagascar', 4),
('LBA', 'Fontana', 'AR', 'Malawi', 1),
('CDG', 'Santa Clarita', 'CA', 'Malaysia', 11),
('YQB', 'Birmingham', 'CO', 'Maldives', 8),
('PBI', 'Oxnard', 'CT', 'Mali', 9),
('FCO', 'Fayetteville', 'DE', 'Malta', 5),
('MIA', 'Moreno Valley', 'FL', 'Marshall Islands', 4),
('JAX', 'Rochester', 'GA', 'Mauritania', 2),
('SLC', 'Glendale', 'HI', 'Mauritius', 6),
('YYJ', 'Huntington Beach', 'ID', 'Mexico', 5),
('TPE', 'Salt Lake City', 'IL', 'Micronesia', 5),
('TPA', 'Grand Rapids', 'IN', 'Moldova', 7),
('OMA', 'Amarillo', 'IA', 'Monaco', 1),
('IAH', 'Yonkers', 'KS', 'Mongolia', 11),
('EWR', 'Aurora', 'KY', 'Montenegro', 5),
('JFK', 'Montgomery', 'LA', 'Morocco', 5),
('CTS', 'Akron', 'ME', 'Mozambique', 8),
('GDN', 'Little Rock', 'MD', 'Myanmar (formerly Burma)', 1),
('CGH', 'Huntsville', 'MA', 'Namibia', 9),
('ABH', 'Augusta', 'MI', 'Nauru', 6),
('TRE', 'Port St. Lucie', 'MN', 'Nepal', 3),
('DTW', 'Grand Prairie', 'MS', 'Netherlands', 1),
('PDX', 'Columbus', 'MO', 'New Zealand', 1),
('DFW', 'Tallahassee', 'MT', 'Nicaragua', 1),
('IAD', 'Overland Park', 'NE', 'Niger', 7),
('SYD', 'Tempe', 'NV', 'Nigeria', 8),
('BCN', 'McKinney', 'NH', 'North Korea', 11),
('DEL', 'Mobile', 'NJ', 'North Macedonia (formerly Macedonia)', 8),
('CPH', 'Cape Coral', 'NM', 'Norway', 1),
('IST', 'Shreveport', 'NY', 'Oman', 4),
('LGA', 'Frisco', 'NC', 'Pakistan', 1),
('PHL', 'Knoxville', 'ND', 'Palau', 1),
('DCA', 'Worcester', 'OH', 'Panama', 11),
('XZO', 'Brownsville', 'OK', 'Papua New Guinea', 4),
('QRD', 'Vancouver', 'OR', 'Paraguay', 8),
('LEU', 'Fort Lauderdale', 'PA', 'Peru', 1),
('LDC', 'Sioux Falls', 'RI', 'Philippines', 6),
('TOJ', 'Ontario', 'SC', 'Poland', 4),
('CKR', 'Chattanooga', 'SD', 'Portugal', 1),
('GYI', 'Providence', 'TN', 'Qatar', 7),
('SRD', 'Newport News', 'TX', 'Romania', 7),
('NMC', 'Rancho Cucamonga', 'UT', 'Russia', 2),
('TSH', 'Santa Rosa', 'VT', 'Rwanda', 1),
('FYN', 'Oceanside', 'VA', 'Saint Kitts and Nevis', 9),
('QTJ', 'Salem', 'WA', 'Saint Lucia', 3),
('FNX', 'Elk Grove', 'WV', 'Saint Vincent and the Grenadines', 9),
('BRS', 'Garden Grove', 'WI', 'Samoa', 1),
('QQY', 'Pembroke Pines', 'WY', 'San Marino', 3),
('DRV', 'Eugene', 'AL', 'Sao Tome and Principe', 1),
('AFT', 'Cary', 'AK', 'Saudi Arabia', 1),
('EZM', 'Springfield', 'AZ', 'Senegal', 11),
('AYN', 'Fort Collins', 'AR', 'Serbia', 9),
('FFA', 'Jackson', 'CA', 'Seychelles', 6),
('JGF', 'Alexandria', 'CO', 'Sierra Leone', 11),
('XUO', 'Hayward', 'CT', 'Singapore', 4),
('CTY', 'Lancaster', 'DE', 'Slovakia', 1),
('VAT', 'Lakewood', 'FL', 'Slovenia', 6),
('WWK', 'Clarksville', 'GA', 'Solomon Islands', 3),
('ZPA', 'Palmdale', 'HI', 'Somalia', 3),
('VUJ', 'Salinas', 'ID', 'South Africa', 11),
('PML', 'Springfield', 'IL', 'South Korea', 2),
('MHE', 'Hollywood', 'IN', 'South Sudan', 2),
('JYP', 'Pasadena', 'IA', 'Spain', 1),
('IXL', 'Sunnyvale', 'KS', 'Sri Lanka', 3),
('MBP', 'Macon', 'KY', 'Sudan', 4),
('IAJ', 'Kansas City', 'LA', 'Suriname', 1),
('OHO', 'Pomona', 'ME', 'Sweden', 1),
('BEV', 'Escondido', 'MD', 'Switzerland', 7),
('BVP', 'Killeen', 'MA', 'Syria', 1),
('IRV', 'Naperville', 'MI', 'Tajikistan', 8),
('LXM', 'Joliet', 'MN', 'Tanzania', 11),
('NCO', 'Bellevue', 'MS', 'Thailand', 9),
('KMN', 'Rockford', 'MO', 'Togo', 1),
('TXZ', 'Savannah', 'MT', 'Tonga', 11),
('TDJ', 'Paterson', 'NE', 'Trinidad and Tobago', 11),
('FBV', 'Torrance', 'NV', 'Tunisia', 7),
('XHW', 'Bridgeport', 'NH', 'Turkey', 1),
('WUB', 'McAllen', 'NJ', 'Turkmenistan', 7),
('JZG', 'Mesquite', 'NM', 'Tuvalu', 8),
('IVD', 'Syracuse', 'NY', 'Uganda', 4),
('PYZ', 'Midland', 'NC', 'Ukraine', 2),
('COQ', 'Pasadena', 'ND', 'United Arab Emirates', 4),
('YVB', 'Murfreesboro', 'OH', 'United Kingdom', 2),
('MLE', 'Miramar', 'OK', 'United States', 9),
('WHL', 'Dayton', 'OR', 'Uruguay', 8),
('FRK', 'Fullerton', 'PA', 'Uzbekistan', 3),
('IBI', 'Olathe', 'RI', 'Vanuatu', 8),
('YER', 'Orange', 'SC', 'Venezuela', 1),
('WYJ', 'Thornton', 'SD', 'Vietnam', 6),
('YDL', 'Roseville', 'TN', 'Yemen', 1),
('MBA', 'Charleston', 'TX', 'Zambia', 1),
('OZK', 'Sterling Heights', 'UT', 'Zimbabwe', 4),
('BRD', 'Gainesville', 'VT', 'Kosovo', 6),
('ZFC', 'Cedar Rapids', 'VA', 'North Cyprus', 3),
('LIP', 'Oxnard', 'WA', 'Sahrawi Arab Democratic Republic', 11),
('MSA', 'Aurora', 'WV', 'Somaliland', 6),
('MRE', 'Moreno Valley', 'WI', 'Taiwan', 3),
('DFY', 'Fontana', 'WY', 'Western Sahara', 6);